//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calabonga.Portal.Config.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calabonga.Portal.Config.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of Admin email should be at least 50 characters.
        /// </summary>
        public static string AppSettings_AdminEmail_Address_of_Admin_email_should_be_at_least_50_characters {
            get {
                return ResourceManager.GetString("AppSettings_AdminEmail_Address_of_Admin_email_should_be_at_least_50_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin email.
        /// </summary>
        public static string AppSettings_AdminEmail_Admin_email {
            get {
                return ResourceManager.GetString("AppSettings_AdminEmail_Admin_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin email - required.
        /// </summary>
        public static string AppSettings_AdminEmail_Admin_email___required {
            get {
                return ResourceManager.GetString("AppSettings_AdminEmail_Admin_email___required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default pager size.
        /// </summary>
        public static string AppSettings_DefaultPagerSize_Default_pager_size {
            get {
                return ResourceManager.GetString("AppSettings_DefaultPagerSize_Default_pager_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default pager size - required.
        /// </summary>
        public static string AppSettings_DefaultPagerSize_Default_pager_size___required {
            get {
                return ResourceManager.GetString("AppSettings_DefaultPagerSize_Default_pager_size___required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain URL.
        /// </summary>
        public static string AppSettings_DomainUrl_Domain_URL {
            get {
                return ResourceManager.GetString("AppSettings_DomainUrl_Domain_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain URL - required.
        /// </summary>
        public static string AppSettings_DomainUrl_Domain_URL___required {
            get {
                return ResourceManager.GetString("AppSettings_DomainUrl_Domain_URL___required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain URL should be at least 256 characters.
        /// </summary>
        public static string AppSettings_DomainUrl_Domain_URL_should_be_at_least_256_characters {
            get {
                return ResourceManager.GetString("AppSettings_DomainUrl_Domain_URL_should_be_at_least_256_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use HTML in email messages.
        /// </summary>
        public static string AppSettings_IsHtmlForEmailMessagesEnabled_Use_HTML_in_email_messages {
            get {
                return ResourceManager.GetString("AppSettings_IsHtmlForEmailMessagesEnabled_Use_HTML_in_email_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event logs enabled.
        /// </summary>
        public static string AppSettings_IsLogging_Event_log {
            get {
                return ResourceManager.GetString("AppSettings_IsLogging_Event_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of Robot email should be at least 50 characters.
        /// </summary>
        public static string AppSettings_RobotEmail_Address_of_Robot_email_should_be_at_least_50_characters {
            get {
                return ResourceManager.GetString("AppSettings_RobotEmail_Address_of_Robot_email_should_be_at_least_50_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot email.
        /// </summary>
        public static string AppSettings_RobotEmail_Robot_email {
            get {
                return ResourceManager.GetString("AppSettings_RobotEmail_Robot_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot email - required.
        /// </summary>
        public static string AppSettings_RobotEmail_Robot_email___required {
            get {
                return ResourceManager.GetString("AppSettings_RobotEmail_Robot_email___required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email server - required.
        /// </summary>
        public static string AppSettings_SmtpClient_Email_server___required {
            get {
                return ResourceManager.GetString("AppSettings_SmtpClient_Email_server___required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email server (example: localhost).
        /// </summary>
        public static string AppSettings_SmtpClient_Email_server__exp__localhost_ {
            get {
                return ResourceManager.GetString("AppSettings_SmtpClient_Email_server__exp__localhost_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email server should be at least 128 characters.
        /// </summary>
        public static string AppSettings_SmtpClient_Email_server_should_be_at_least_128_characters {
            get {
                return ResourceManager.GetString("AppSettings_SmtpClient_Email_server_should_be_at_least_128_characters", resourceCulture);
            }
        }
    }
}
